---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by info.
--- DateTime: 02.05.2021 14:48
---

github = "https://raw.githubusercontent.com/Seniorendi/Lua-Projects/master/"

programs = {
    mecpus = {link= github.."src/ME%20Cpus/startup.lua", name="ME Cpus"}
}

local args = {...}

--TODO