---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by info.
--- DateTime: 02.05.2021 14:48
---

local githuburl = "https://raw.githubusercontent.com/Seniorendi/Lua-Projects/master/src/Programs.txt"

--TODO: Safe this in a file
local firstStart = true

programs = {}

local args = {...}

function loadSources()
    local dl, error = http.get(githuburl)

    if dl then
        programs = textutils.unserialise(dl.readAll())
        dl.close()
    else
        exit("Could not load programs.txt. Please contact srendi on github or discord.".. error)
    end
end

if firstStart then
    print("Prepare first start...")
    if fs.exists("startup") or fs.exists("startup.lua") then
        exit("Delete the startup file and install this program as installer!")
    end
    print("Download sources...")
    loadSources()
    --Create startup file
    --TODO: This is just a test for the sources
    for k, v in pairs(programs) do
        print(k, v)
    end
end


--TODO