---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Srendi.
--- DateTime: 01.05.2021 23:47
---

function wrapPs(peripheralName)
    periTab={}
    sideTab={}
    if peripheralName==nil then
        print("Could not find".. peripheralName)
    end
    local peripherals = peripheral.getNames()
    local i2 = 1
    for i =1, #peripherals do
        if peripheral.getType(peripherals[i])==peripheralName then
            periTab[i2]=peripheral.wrap(peripherals[i])
            sideTab[i2]=peripherals[i]
            i2=i2+1
        end
    end
    if periTab~={} then
        return periTab,sideTab
    else
        return nil
    end
end

computers = wrapPs("computer")

computerList = {
    me = {name="mecpu", label="Me CPUs", computer=nil}
}

monitor = peripheral.wrap("top")

function prepareComputers()
    for k, v in pairs(computers) do
        for k1, v1 in pairs(computerList) do
            if v.getLabel() == v1.name then
                print(v1.label)
                v1.computer = v
            end
        end
    end
end

prepareComputers()

while true do
    table.sort(computerList)
    for i = 1, #computerList do
        local k, v = computerList[i], computerList[i]
        local y = 3*1
        monitor.setCursorPos(3, y)
        monitor.write(computerList[i].label .."...")
        Monitor.setTextColor(computerList[i].computer.isOn() and colors.green or colors.red)
        Monitor.write(computerList[i].computer.isOn() and "Online" or "Offline")
    end
end