---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Srendi.
--- DateTime: 01.05.2021 23:47
---

function wrapPs(peripheralName)
    periTab={}
    sideTab={}
    if peripheralName==nil then
        print("Could not find".. peripheralName)
    end
    local peripherals = peripheral.getNames()
    local i2 = 1
    for i =1, #peripherals do
        if peripheral.getType(peripherals[i])==peripheralName then
            periTab[i2]=peripheral.wrap(peripherals[i])
            sideTab[i2]=peripherals[i]
            i2=i2+1
        end
    end
    if periTab~={} then
        return periTab,sideTab
    else
        return nil
    end
end

computers = wrapPs("computer")

for k, v in pairs(computers) do
    print(k, v)
end